const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const fillSequence=(bank,count)=>{let out=[];while(out.length<count)out.push(...shuffle(bank));return out.slice(0,count)};
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.open)));
$$('.back').forEach(b=>b.addEventListener('click',()=>openView('home')));
function openView(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
$('#fullscreenBtn').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){}});
document.addEventListener('fullscreenchange',()=>$('#fullscreenBtn').textContent=document.fullscreenElement?'Exit Full Screen':'Full Screen');

// WORD FLASH
const wordFlashBanks={
 'Short a':['cat','map','jam','hand','flag','stamp','crab','black','plant','sand','snap','trap','clap','camp','glass','stand','track','branch','crash','grand'],
 'Short i':['sit','fin','milk','ship','grin','stick','swim','clip','drip','fish','gift','hill','mint','spin','brick','trim','slip','print','chill','quick'],
 'Short o':['hot','log','rock','stop','frog','clock','pond','shop','spot','block','drop','chop','strong','cross','mop','plot','sock','not','job','fox'],
 'Short e':['bed','red','step','best','tent','shell','dress','left','fresh','chest','web','rest','sled','neck','press','check','blend','help','spent','smell'],
 'Short u':['sun','cup','jump','truck','drum','brush','club','hunt','must','duck','plug','crush','luck','stump','run','gum','dust','shut','bump','trust'],
 'Mixed Short Vowels':['map','sit','hot','bed','sun','flag','ship','frog','tent','truck','stamp','brick','clock','fresh','brush','plant','spin','shop','left','jump'],
 'Initial / Final s-Blends':['stop','spin','step','skin','smell','snack','spot','best','fast','rest','mask','desk','crisp','trust','stamp','spent','stand','swim','slip','skunk'],
 'l- and t-Blends':['clap','flag','plug','glad','black','plan','trip','drum','track','frog','clip','flat','glass','plant','truck','dress','trim','crab','drop','blend'],
 'r-Blends':['crab','drum','frog','grin','prize','track','brush','crop','drag','fresh','grab','press','trip','brick','grass','crash','drink','print','truck','grand'],
 'ch and sh':['chip','chat','chop','much','rich','ship','shop','shut','fish','wish','chest','shell','brush','fresh','crush','chill','shock','shack','dish','rush'],
 'th, wh, and ck':['this','that','them','thin','thick','when','whip','whiz','back','rock','duck','check','clock','track','brick','stick','which','with','whisk','shock'],
 'Silent-e Long a':['make','game','late','same','plane','grade','shape','brave','trade','place','frame','skate','chase','whale','shade','grape','stage','plate','crane','space'],
 'Silent-e Long i':['time','ride','bike','line','smile','drive','white','shine','slide','prize','stripe','while','spine','bride','quite','chime','slice','hide','wide','spike'],
 'Silent-e Long o':['home','note','rope','stone','close','globe','those','smoke','broke','hope','chose','slope','stove','phone','whole','joke','rose','cone','bone','woke'],
 'Silent-e Long u':['cube','tune','cute','mule','use','June','rule','flute','huge','tube','fume','dune','rude','pure','mute','fuse','duke','prune','plume','excuse'],
 'Mixed Silent-e':['make','ride','home','cube','shape','shine','stone','tune','grade','smile','rope','flute','place','white','globe','huge','trade','slide','hope','rule'],
 'igh and oa':['light','night','right','bright','sight','high','might','road','boat','coat','goat','float','toast','coach','loaf','roast','flight','tight','oak','goal'],
 'ee and oe':['see','green','feet','sleep','week','deep','tree','three','seed','feel','toe','hoe','foe','doe','goes','free','need','keep','peel','queen'],
 'ai / ay / oi / oy':['rain','train','paint','mail','wait','play','stay','day','clay','gray','coin','join','soil','point','boy','toy','joy','enjoy','chain','spray'],
 'au and aw':['haul','pause','cause','fault','launch','draw','saw','straw','claw','hawk','crawl','lawn','yawn','raw','shawl','August','author','sauce','dawn','paws'],
 'Unpredictable Vowel Teams':['head','bread','great','steak','snow','grow','cow','town','book','moon','look','room','cloud','house','could','group','soup','touch','young','should'],
 'Vowel-r':['car','star','farm','park','fork','storm','short','north','her','term','bird','first','turn','curl','shirt','start','sharp','horn','third','burst'],
 'Silent Letters':['knee','knock','knife','write','wrong','wrap','lamb','thumb','sign','gnaw','wrist','knot','wreck','climb','comb','knit','known','wrote','crumb','gnat'],
 'Complex Consonants':['badge','bridge','edge','match','catch','pitch','duck','milk','city','cent','giant','gem','judge','change','pack','magic','race','cage','fetch','ridge']
};
const wfPattern=$('#wfPattern');Object.keys(wordFlashBanks).forEach(k=>wfPattern.add(new Option(k,k)));
let wf={seq:[],i:0,t:null,paused:false,phase:'ready'};
$('#wfMode').addEventListener('change',()=>$('#wfAutoOptions').classList.toggle('hidden',$('#wfMode').value!=='auto'));
$('#wfStart').addEventListener('click',startWF);$('#wfRestart').addEventListener('click',startWF);$('#wfPause').addEventListener('click',()=>{wf.paused=!wf.paused;clearTimeout(wf.t);$('#wfPause').textContent=wf.paused?'Resume':'Pause';if(!wf.paused)wfAutoWord()});
$('#wfAction').addEventListener('click',()=>{if(wf.phase==='show'){wf.phase='hide';$('#wfWord').textContent='';$('#wfPrompt').textContent='Think. Read it in your head.';$('#wfAction').textContent='Reveal'}else if(wf.phase==='hide'){wf.phase='reveal';$('#wfWord').textContent=wf.seq[wf.i];$('#wfPrompt').textContent='Read it again.';$('#wfAction').textContent='Next Word'}else{wf.i++;wf.phase='show';if(wf.i>=wf.seq.length)return wfDone();wfGuidedWord()}});
function startWF(){clearTimeout(wf.t);wf.seq=fillSequence(wordFlashBanks[wfPattern.value],Number($('#wfCount').value));wf.i=0;wf.paused=false;$('#wfPause').textContent='Pause';$('#wfRestart').classList.remove('hidden');if($('#wfMode').value==='auto'){wfAutoWord()}else{wf.phase='show';wfGuidedWord()}}
function wfGuidedWord(){setCounter('#wfCounter',wf.i,wf.seq.length);$('#wfWord').textContent=wf.seq[wf.i];$('#wfPrompt').textContent='Read the word.';$('#wfAction').textContent='Hide';$('#wfAction').classList.remove('hidden');$('#wfPause').classList.add('hidden')}
function wfAutoWord(){if(wf.paused)return;if(wf.i>=wf.seq.length)return wfDone();setCounter('#wfCounter',wf.i,wf.seq.length);$('#wfWord').textContent=wf.seq[wf.i];$('#wfPrompt').textContent='';$('#wfAction').classList.add('hidden');$('#wfPause').classList.remove('hidden');wf.t=setTimeout(()=>{$('#wfWord').textContent='';wf.t=setTimeout(()=>{wf.i++;wfAutoWord()},Number($('#wfBlankTime').value))},Number($('#wfWordTime').value))}
function wfDone(){clearTimeout(wf.t);$('#wfWord').textContent='Complete';$('#wfPrompt').textContent='';$('#wfAction').classList.add('hidden');$('#wfPause').classList.add('hidden');$('#wfCounter').textContent=`${wf.seq.length} words`}

// HIGH-FREQUENCY WORDS
const hfData={
 beginning:[
  ['and',[['a','/ă/',0],['n','/n/',0],['d','/d/',0]]],['can',[['c','/k/',0],['a','/ă/',0],['n','/n/',0]]],['in',[['i','/ĭ/',0],['n','/n/',0]]],['it',[['i','/ĭ/',0],['t','/t/',0]]],['at',[['a','/ă/',0],['t','/t/',0]]],['not',[['n','/n/',0],['o','/ŏ/',0],['t','/t/',0]]],['run',[['r','/r/',0],['u','/ŭ/',0],['n','/n/',0]]],['up',[['u','/ŭ/',0],['p','/p/',0]]],['get',[['g','/g/',0],['e','/ĕ/',0],['t','/t/',0]]],['red',[['r','/r/',0],['e','/ĕ/',0],['d','/d/',0]]],['big',[['b','/b/',0],['i','/ĭ/',0],['g','/g/',0]]],['did',[['d','/d/',0],['i','/ĭ/',0],['d','/d/',0]]],['am',[['a','/ă/',0],['m','/m/',0]]],['ran',[['r','/r/',0],['a','/ă/',0],['n','/n/',0]]],['on',[['o','/ŏ/',0],['n','/n/',0]]]
 ],
 developing:[
  ['make',[['m','/m/',0],['a_e','/ā/',0],['k','/k/',0]]],['came',[['c','/k/',0],['a_e','/ā/',0],['m','/m/',0]]],['ride',[['r','/r/',0],['i_e','/ī/',0],['d','/d/',0]]],['white',[['wh','/w/',0],['i_e','/ī/',0],['t','/t/',0]]],['here',[['h','/h/',0],['ere','/ēr/',1]]],['ate',[['a_e','/ā/',0],['t','/t/',0]]],['like',[['l','/l/',0],['i_e','/ī/',0],['k','/k/',0]]],['home',[['h','/h/',0],['o_e','/ō/',0],['m','/m/',0]]],['time',[['t','/t/',0],['i_e','/ī/',0],['m','/m/',0]]],['these',[['th','/th/',0],['ese','/ēz/',1]]],['see',[['s','/s/',0],['ee','/ē/',0]]],['day',[['d','/d/',0],['ay','/ā/',0]]],['play',[['p','/p/',0],['l','/l/',0],['ay','/ā/',0]]],['out',[['ou','/ow/',0],['t','/t/',0]]],['down',[['d','/d/',0],['ow','/ow/',0],['n','/n/',0]]]
 ],
 tricky:[
  ['said',[['s','/s/',0],['ai','/ĕ/',1],['d','/d/',0]]],['was',[['w','/w/',0],['a','/ŭ/',1],['s','/z/',1]]],['some',[['s','/s/',0],['o','/ŭ/',1],['m','/m/',0],['e','silent',1]]],['come',[['c','/k/',0],['o','/ŭ/',1],['m','/m/',0],['e','silent',1]]],['does',[['d','/d/',0],['oe','/ŭ/',1],['s','/z/',1]]],['you',[['y','/y/',0],['ou','/oo/',1]]],['they',[['th','/th/',0],['ey','/ā/',1]]],['of',[['o','/ŭ/',1],['f','/v/',1]]],['were',[['w','/w/',0],['ere','/er/',1]]],['where',[['wh','/w/',0],['ere','/air/',1]]],['again',[['a','/ə/',1],['g','/g/',0],['ai','/ĕ/',1],['n','/n/',0]]],['because',[['be','/bē/ or /bə/',1],['cause','/kŭz/',1]]]
 ]
};hfData.mixed=[...hfData.beginning,...hfData.developing,...hfData.tricky];
let hf={seq:[],i:0,t:null,paused:false,phase:'show'};
$('#hfMode').addEventListener('change',()=>$('#hfAutoOptions').classList.toggle('hidden',$('#hfMode').value!=='auto'));
$('#hfStart').addEventListener('click',startHF);$('#hfRestart').addEventListener('click',startHF);$('#hfPause').addEventListener('click',()=>{hf.paused=!hf.paused;clearTimeout(hf.t);$('#hfPause').textContent=hf.paused?'Resume':'Pause';if(!hf.paused)hfAutoWord()});
$('#hfAction').addEventListener('click',()=>{const item=hf.seq[hf.i];if(hf.phase==='show'){hf.phase='hide';$('#hfWord').textContent='';$('#hfMap').classList.add('hidden');$('#hfPrompt').textContent='Read it in your head.';$('#hfAction').textContent='Reveal'}else if(hf.phase==='hide'){hf.phase='reveal';$('#hfWord').textContent=item[0];if($('#hfMapping').checked)renderSoundMap(item[1]);$('#hfPrompt').textContent=$('#hfMapping').checked?'Connect the sounds to the spelling.':'Read the word again.';$('#hfAction').textContent='Next Word'}else{hf.i++;hf.phase='show';if(hf.i>=hf.seq.length)return hfDone();hfGuidedWord()}});
function startHF(){clearTimeout(hf.t);hf.seq=fillSequence(hfData[$('#hfSet').value],Number($('#hfCount').value));hf.i=0;hf.paused=false;$('#hfPause').textContent='Pause';$('#hfRestart').classList.remove('hidden');if($('#hfMode').value==='auto')hfAutoWord();else{hf.phase='show';hfGuidedWord()}}
function hfGuidedWord(){setCounter('#hfCounter',hf.i,hf.seq.length);$('#hfWord').textContent=hf.seq[hf.i][0];$('#hfMap').classList.add('hidden');$('#hfPrompt').textContent='Read the word.';$('#hfAction').textContent='Hide';$('#hfAction').classList.remove('hidden');$('#hfPause').classList.add('hidden')}
function renderSoundMap(map){$('#hfMap').innerHTML=map.map(x=>`<div class="sound-box ${x[2]?'tricky':''}"><b>${escapeHtml(x[0])}</b><small>${escapeHtml(x[1])}</small></div>`).join('');$('#hfMap').classList.remove('hidden')}
function hfAutoWord(){if(hf.paused)return;if(hf.i>=hf.seq.length)return hfDone();setCounter('#hfCounter',hf.i,hf.seq.length);$('#hfWord').textContent=hf.seq[hf.i][0];$('#hfMap').classList.add('hidden');$('#hfPrompt').textContent='';$('#hfAction').classList.add('hidden');$('#hfPause').classList.remove('hidden');hf.t=setTimeout(()=>{$('#hfWord').textContent='';hf.t=setTimeout(()=>{hf.i++;hfAutoWord()},Number($('#hfBlankTime').value))},Number($('#hfWordTime').value))}
function hfDone(){clearTimeout(hf.t);$('#hfWord').textContent='Complete';$('#hfMap').classList.add('hidden');$('#hfPrompt').textContent='';$('#hfAction').classList.add('hidden');$('#hfPause').classList.add('hidden');$('#hfCounter').textContent=`${hf.seq.length} words`}

// MORPHOLOGY
const M=(w,parts,spot,build,check)=>({w,parts,spot,build,check});
const morphologyBanks={
 '1':{label:'1. Compound Words',group:'Foundations',items:[M('backpack',['back','pack'],[0,1],['back','pack','a pack carried on the back'],'Luis placed his books in his backpack.'),M('sunlight',['sun','light'],[0,1],['sun','light','light from the sun'],'Sunlight came through the window.'),M('classroom',['class','room'],[0,1],['class','room','a room used for a class'],'The classroom was quiet.'),M('rainfall',['rain','fall'],[0,1],['rain','fall','rain that falls / amount of rain'],'Heavy rainfall filled the puddles.'),M('playground',['play','ground'],[0,1],['play','ground','ground used for play'],'Children ran across the playground.'),M('sunset',['sun','set'],[0,1],['sun','set','the time the sun appears to go down'],'We watched the sunset.'),M('bedroom',['bed','room'],[0,1],['bed','room','a room for sleeping'],'She read in her bedroom.'),M('snowstorm',['snow','storm'],[0,1],['snow','storm','a storm with snow'],'The snowstorm closed school.'),M('toothbrush',['tooth','brush'],[0,1],['tooth','brush','a brush for cleaning teeth'],'He packed his toothbrush.'),M('seashell',['sea','shell'],[0,1],['sea','shell','a shell found by the sea'],'She found a seashell.'),M('farmhouse',['farm','house'],[0,1],['farm','house','a house on a farm'],'The farmhouse stood near the field.'),M('weekday',['week','day'],[0,1],['week','day','a day in the working/school week'],'Monday is a weekday.'),M('daylight',['day','light'],[0,1],['day','light','natural light during the day'],'They left at daylight.'),M('rainwater',['rain','water'],[0,1],['rain','water','water that comes from rain'],'The barrel collected rainwater.'),M('lunchroom',['lunch','room'],[0,1],['lunch','room','a room where lunch is eaten'],'They met in the lunchroom.'),M('weekend',['week','end'],[0,1],['week','end','the end of the week'],'We rested over the weekend.'),M('raincoat',['rain','coat'],[0,1],['rain','coat','a coat worn in rain'],'Mila put on her raincoat.'),M('schoolyard',['school','yard'],[0,1],['school','yard','the yard around a school'],'Students crossed the schoolyard.'),M('moonlight',['moon','light'],[0,1],['moon','light','light from the moon'],'The path shone in the moonlight.'),M('bedtime',['bed','time'],[0,1],['bed','time','the time to go to bed'],'At bedtime, he read a book.'),M('sunflower',['sun','flower'],[0,1],['sun','flower','a flower whose name connects to the sun'],'The sunflower grew tall.') ]},
 '2':{label:'2. Inflectional Endings',group:'Foundations',items:[M('jumps',['jump','s'],[0,1],['jump','-s','one person or thing does the action'],'The player jumps over the line.'),M('boxes',['box','es'],[0,1],['box','-es','more than one box'],'Two boxes sat by the door.'),M('helps',['help','s'],[0,1],['help','-s','one person or thing helps'],'A friend helps.'),M('wishes',['wish','es'],[0,1],['wish','-es','one person wishes'],'She wishes for rain.'),M('helping',['help','ing'],[0,1],['help','-ing','the action is in progress'],'Maya is helping her partner.'),M('resting',['rest','ing'],[0,1],['rest','-ing','the action is in progress'],'Ben is resting.'),M('playing',['play','ing'],[0,1],['play','-ing','the action is in progress'],'They are playing outside.'),M('washing',['wash','ing'],[0,1],['wash','-ing','the action is in progress'],'He is washing the brushes.'),M('jumped',['jump','ed'],[0,1],['jump','-ed','the action already happened'],'They jumped over the puddle.'),M('played',['play','ed'],[0,1],['play','-ed','the action already happened'],'They played after school.'),M('rested',['rest','ed'],[0,1],['rest','-ed','the action already happened'],'The players rested.'),M('wished',['wish','ed'],[0,1],['wish','-ed','the action already happened'],'She wished for snow.'),M('prints',['print','s'],[0,1],['print','-s','one person prints'],'Maya prints a sign.'),M('floating',['float','ing'],[0,1],['float','-ing','the action is happening'],'The boats are floating.'),M('watches',['watch','es'],[0,1],['watch','-es','one person watches'],'Lee watches the boats.'),M('cleaned',['clean','ed'],[0,1],['clean','-ed','the action already happened'],'Ana cleaned the bench.'),M('started',['start','ed'],[0,1],['start','-ed','the action already happened'],'The class started early.'),M('brushes',['brush','es'],[0,1],['brush','-es','one person brushes'],'A worker brushes the seats.'),M('sailing',['sail','ing'],[0,1],['sail','-ing','the action is happening'],'The boats were sailing.'),M('shouted',['shout','ed'],[0,1],['shout','-ed','the action already happened'],'Children shouted.'),M('packed',['pack','ed'],[0,1],['pack','-ed','the action already happened'],'They packed two boxes.') ]},
 '3':{label:'3. Reliable Two-Syllable Words',group:'Foundations',items:[M('rabbit',['rab','bit'],[],['rab','bit','blend the chunks'],'The rabbit sat by the basket.'),M('napkin',['nap','kin'],[],['nap','kin','blend the chunks'],'The napkin was beside the plate.'),M('picnic',['pic','nic'],[],['pic','nic','blend the chunks'],'We packed a picnic.'),M('basket',['bas','ket'],[],['bas','ket','blend the chunks'],'The basket was full.'),M('music',['mu','sic'],[],['mu','sic','blend and check the familiar word'],'Music played softly.'),M('robot',['ro','bot'],[],['ro','bot','blend and check'],'The robot moved forward.'),M('magnet',['mag','net'],[],['mag','net','blend and check'],'The magnet stuck to the door.'),M('tulip',['tu','lip'],[],['tu','lip','blend and check'],'A tulip grew nearby.'),M('student',['stu','dent'],[],['stu','dent','blend and check'],'The student opened a book.'),M('moment',['mo','ment'],[],['mo','ment','blend and check'],'Wait a moment.'),M('dentist',['den','tist'],[],['den','tist','blend and check'],'The dentist checked the tooth.'),M('helmet',['hel','met'],[],['hel','met','blend and check'],'Wear a helmet.'),M('cabin',['cab','in'],[],['cab','in','blend and check'],'The cabin was quiet.'),M('program',['pro','gram'],[],['pro','gram','blend and check'],'The program began at noon.'),M('problem',['prob','lem'],[],['prob','lem','blend and check'],'She solved the problem.'),M('hotel',['ho','tel'],[],['ho','tel','blend and check'],'They stayed at a hotel.'),M('comic',['com','ic'],[],['com','ic','blend and check'],'He read a comic.'),M('velvet',['vel','vet'],[],['vel','vet','blend and check'],'The curtain felt like velvet.'),M('finish',['fin','ish'],[],['fin','ish','blend and check'],'Please finish the page.') ]},
 '4':{label:'4. Common Prefixes',group:'Affixes & Multisyllabic',items:[M('unsafe',['un','safe'],[0],['un- = not','safe','not safe'],'The broken bridge was unsafe.'),M('unfair',['un','fair'],[0],['un- = not','fair','not fair'],'The rule felt unfair.'),M('unclear',['un','clear'],[0],['un- = not','clear','not clear'],'The directions were unclear.'),M('reread',['re','read'],[0],['re- = again','read','read again'],'Reread the sentence.'),M('rebuild',['re','build'],[0],['re- = again','build','build again'],'Workers will rebuild the wall.'),M('replay',['re','play'],[0],['re- = again','play','play again'],'Replay the recording.'),M('dislike',['dis','like'],[0],['dis- changes/opposes','like','not like'],'I dislike loud alarms.'),M('disagree',['dis','agree'],[0],['dis- changes/opposes','agree','not agree'],'They disagree about the answer.'),M('disconnect',['dis','connect'],[0],['dis- = apart/not','connect','separate the connection'],'Disconnect the cable.'),M('misread',['mis','read'],[0],['mis- = wrongly','read','read incorrectly'],'I misread the question.'),M('misplace',['mis','place'],[0],['mis- = wrongly','place','put in the wrong place'],'Do not misplace your keys.'),M('misunderstand',['mis','understand'],[0],['mis- = wrongly','understand','understand incorrectly'],'I misunderstood the directions.'),M('preview',['pre','view'],[0],['pre- = before','view','view beforehand'],'We previewed the chapter.'),M('prepay',['pre','pay'],[0],['pre- = before','pay','pay beforehand'],'You can prepay online.'),M('preschool',['pre','school'],[0],['pre- = before','school','school before elementary grades'],'The child attends preschool.'),M('repaint',['re','paint'],[0],['re- = again','paint','paint again'],'They will repaint the room.'),M('unusual',['un','usual'],[0],['un- = not','usual','not usual'],'That was unusual weather.'),M('dishonest',['dis','honest'],[0],['dis- = not/opposite','honest','not honest'],'The dishonest claim was corrected.'),M('miscount',['mis','count'],[0],['mis- = wrongly','count','count incorrectly'],'I miscounted the blocks.'),M('preseason',['pre','season'],[0],['pre- = before','season','before the season'],'Practice begins in preseason.'),M('reconnect',['re','connect'],[0],['re- = again','connect','connect again'],'Reconnect the wire.') ]},
 '5':{label:'5. Derivational Suffixes',group:'Affixes & Multisyllabic',items:[M('helpful',['help','ful'],[1],['help','-ful','providing or full of help'],'The guide was helpful.'),M('helpless',['help','less'],[1],['help','-less','without help or unable to help oneself'],'The kitten seemed helpless.'),M('careful',['care','ful'],[1],['care','-ful','showing care'],'Be careful on the stairs.'),M('careless',['care','less'],[1],['care','-less','without enough care'],'A careless mistake changed the total.'),M('peaceful',['peace','ful'],[1],['peace','-ful','full of peace/calm'],'The lake was peaceful.'),M('fearless',['fear','less'],[1],['fear','-less','without fear'],'The fearless climber kept going.'),M('endless',['end','less'],[1],['end','-less','without an end'],'The road seemed endless.'),M('restless',['rest','less'],[1],['rest','-less','unable to rest'],'He felt restless.'),M('kindness',['kind','ness'],[1],['kind','-ness','the quality of being kind'],'Her kindness mattered.'),M('darkness',['dark','ness'],[1],['dark','-ness','the state of being dark'],'Darkness filled the room.'),M('sickness',['sick','ness'],[1],['sick','-ness','the state of being sick'],'The sickness spread quickly.'),M('weakness',['weak','ness'],[1],['weak','-ness','a state or point of being weak'],'The crack was a weakness.'),M('payment',['pay','ment'],[1],['pay','-ment','an act or result of paying'],'The payment was due Friday.'),M('enjoyment',['enjoy','ment'],[1],['enjoy','-ment','the state/result of enjoying'],'Reading brought enjoyment.'),M('treatment',['treat','ment'],[1],['treat','-ment','the act/process of treating'],'The plant received treatment.'),M('development',['develop','ment'],[1],['develop','-ment','the process/result of developing'],'The project showed development.'),M('brightness',['bright','ness'],[1],['bright','-ness','the quality of being bright'],'Adjust the screen brightness.'),M('shipment',['ship','ment'],[1],['ship','-ment','goods sent or the act of sending'],'The shipment arrived.'),M('amazement',['amaze','ment'],[1],['amaze','-ment','a state of being amazed'],'She stared in amazement.'),M('thankful',['thank','ful'],[1],['thank','-ful','feeling or showing thanks'],'We were thankful.'),M('powerless',['power','less'],[1],['power','-less','without power'],'The building was powerless.') ]},
 '6':{label:'6. Prefixes + Suffixes',group:'Affixes & Multisyllabic',items:[M('unhelpful',['un','help','ful'],[0,2],['help','helpful','unhelpful'],'The unclear directions were unhelpful.'),M('unkindness',['un','kind','ness'],[0,2],['kind','kindness','unkindness'],'The story showed unkindness.'),M('disagreement',['dis','agree','ment'],[0,2],['agree','disagree','disagreement'],'The disagreement ended.'),M('misplacement',['mis','place','ment'],[0,2],['place','misplace','misplacement'],'The misplacement caused a delay.'),M('prepayment',['pre','pay','ment'],[0,2],['pay','prepay','prepayment'],'Prepayment is required.'),M('disrespectful',['dis','respect','ful'],[0,2],['respect','respectful','disrespectful'],'The comment was disrespectful.'),M('rereading',['re','read','ing'],[0,2],['read','reread','rereading'],'Rereading helped me understand.'),M('replayed',['re','play','ed'],[0,2],['play','replay','replayed'],'We replayed the clip.'),M('disconnecting',['dis','connect','ing'],[0,2],['connect','disconnect','disconnecting'],'He is disconnecting the cable.'),M('misunderstandings',['mis','understand','ings'],[0,2],['understand','misunderstand','misunderstandings'],'The group cleared up misunderstandings.'),M('repayment',['re','pay','ment'],[0,2],['pay','repay','repayment'],'The repayment is due.'),M('miscounted',['mis','count','ed'],[0,2],['count','miscount','miscounted'],'I miscounted the votes.'),M('disconnected',['dis','connect','ed'],[0,2],['connect','disconnect','disconnected'],'The device was disconnected.'),M('preheated',['pre','heat','ed'],[0,2],['heat','preheat','preheated'],'The oven was preheated.'),M('misplaced',['mis','place','ed'],[0,2],['place','misplace','misplaced'],'I misplaced the folder.'),M('unfairness',['un','fair','ness'],[0,2],['fair','unfair','unfairness'],'They discussed the unfairness.'),M('reusable',['re','use','able'],[0,2],['use','reuse','reusable'],'Bring a reusable bottle.'),M('unthinkable',['un','think','able'],[0,2],['think','thinkable','unthinkable'],'The damage once seemed unthinkable.') ]},
 '7':{label:'7. Three-Syllable Words',group:'Affixes & Multisyllabic',items:[M('carefully',['care','ful','ly'],[0,1],['care','careful','carefully'],'Read the directions carefully.'),M('powerless',['pow','er','less'],[2],['power','-less','powerless'],'The town was powerless.'),M('disagreement',['dis','agree','ment'],[0,2],['agree','disagree','disagreement'],'The disagreement continued.'),M('replaying',['re','play','ing'],[0,2],['play','replay','replaying'],'They are replaying the scene.'),M('important',['im','por','tant'],[],['im','por','tant'],'The detail is important.'),M('remember',['re','mem','ber'],[0],['re','mem','ber'],'Remember the rule.'),M('animal',['an','i','mal'],[],['an','i','mal'],'The animal moved quickly.'),M('holiday',['hol','i','day'],[],['hol','i','day'],'School closes for the holiday.'),M('computer',['com','pu','ter'],[],['com','pu','ter'],'The computer restarted.'),M('yesterday',['yes','ter','day'],[],['yes','ter','day'],'It rained yesterday.'),M('wonderful',['won','der','ful'],[2],['wonder','-ful','wonderful'],'The trip was wonderful.'),M('paragraph',['par','a','graph'],[2],['par','a','graph'],'Read the paragraph.'),M('visitor',['vis','i','tor'],[],['vis','i','tor'],'A visitor arrived.'),M('adventure',['ad','ven','ture'],[2],['ad','ven','ture'],'The hike became an adventure.'),M('afternoon',['af','ter','noon'],[],['af','ter','noon'],'We met in the afternoon.'),M('difficult',['dif','fi','cult'],[],['dif','fi','cult'],'The puzzle was difficult.'),M('fantastic',['fan','tas','tic'],[],['fan','tas','tic'],'The show was fantastic.'),M('attention',['at','ten','tion'],[2],['at','ten','tion'],'Pay attention to the pattern.'),M('different',['dif','fer','ent'],[],['dif','fer','ent'],'The answers were different.') ]},
 '8':{label:'8. Stable Academic Endings',group:'Affixes & Multisyllabic',items:[M('action',['ac','tion'],[1],['-tion','stable ending','action'],'The action happened quickly.'),M('invention',['inven','tion'],[1],['inven','-tion','invention'],'The invention solved a problem.'),M('decision',['deci','sion'],[1],['deci','-sion','decision'],'We made a decision.'),M('conclusion',['conclu','sion'],[1],['conclu','-sion','conclusion'],'Write a conclusion.'),M('picture',['pic','ture'],[1],['pic','-ture','picture'],'Study the picture.'),M('culture',['cul','ture'],[1],['cul','-ture','culture'],'The class learned about culture.'),M('structure',['struc','ture'],[1],['struc','-ture','structure'],'The structure was strong.'),M('feature',['fea','ture'],[1],['fea','-ture','feature'],'This feature saves time.'),M('dangerous',['danger','ous'],[1],['danger','-ous','dangerous'],'The cliff was dangerous.'),M('famous',['fam','ous'],[1],['fam','-ous','famous'],'The bridge is famous.'),M('active',['act','ive'],[1],['act','-ive','active'],'Stay active.'),M('creative',['creat','ive'],[1],['create','-ive','creative'],'She found a creative solution.'),M('natural',['natur','al'],[1],['nature','-al','natural'],'Use natural light.'),M('final',['fin','al'],[1],['fin','-al','final'],'This is the final round.'),M('activity',['activ','ity'],[1],['active','-ity','activity'],'Choose an activity.'),M('equality',['equal','ity'],[1],['equal','-ity','equality'],'They discussed equality.'),M('production',['produc','tion'],[1],['produc','-tion','production'],'Production increased.'),M('expression',['expres','sion'],[1],['expres','-sion','expression'],'Her expression changed.'),M('curious',['curi','ous'],[1],['curi','-ous','curious'],'The student was curious.'),M('supportive',['support','ive'],[1],['support','-ive','supportive'],'The group was supportive.'),M('locality',['local','ity'],[1],['local','-ity','locality'],'The species is common in this locality.') ]},
 '9':{label:'9. Base-Word Spelling Changes',group:'Affixes & Multisyllabic',items:[M('making',['make','ing'],[0,1],['make','drop final e','making'],'She is making a model.'),M('hoping',['hope','ing'],[0,1],['hope','drop final e','hoping'],'We are hoping for sun.'),M('using',['use','ing'],[0,1],['use','drop final e','using'],'They are using rulers.'),M('creating',['create','ing'],[0,1],['create','drop final e','creating'],'Students are creating posters.'),M('running',['run','ing'],[0,1],['run','double final consonant','running'],'He is running.'),M('sitting',['sit','ing'],[0,1],['sit','double final consonant','sitting'],'She is sitting.'),M('planned',['plan','ed'],[0,1],['plan','double final consonant','planned'],'We planned the trip.'),M('stopped',['stop','ed'],[0,1],['stop','double final consonant','stopped'],'The rain stopped.'),M('tried',['try','ed'],[0,1],['try','change y to i','tried'],'She tried again.'),M('carried',['carry','ed'],[0,1],['carry','change y to i','carried'],'He carried the bag.'),M('studies',['study','es'],[0,1],['study','change y to i','studies'],'She studies nightly.'),M('hurrying',['hurry','ing'],[0,1],['hurry','keep y before -ing','hurrying'],'He is hurrying.'),M('writing',['write','ing'],[0,1],['write','drop final e','writing'],'She is writing.'),M('copied',['copy','ed'],[0,1],['copy','change y to i','copied'],'He copied the chart.'),M('dancing',['dance','ing'],[0,1],['dance','drop final e','dancing'],'They are dancing.'),M('admitted',['admit','ed'],[0,1],['admit','double final consonant','admitted'],'He admitted the error.'),M('beginning',['begin','ing'],[0,1],['begin','double final consonant','beginning'],'The movie is beginning.'),M('hoped',['hope','ed'],[0,1],['hope','drop final e','hoped'],'We hoped for better weather.') ]},
 '10':{label:'10. struct & form',group:'Roots & Word Families',items:[M('structure',['struct','ure'],[0],['struct = build','structure','something built/organized'],'The bridge structure is strong.'),M('construct',['con','struct'],[1],['struct = build','construct','build something'],'Workers construct the frame.'),M('construction',['con','struct','ion'],[1],['struct = build','construct','construction'],'Construction began Monday.'),M('instruct',['in','struct'],[1],['struct = build','instruct','teach/give directions'],'The coach will instruct the group.'),M('structural',['struct','ural'],[0],['struct = build','structure','structural'],'The engineer checked structural damage.'),M('reconstruct',['re','con','struct'],[2],['struct = build','construct','reconstruct = build again'],'They will reconstruct the wall.'),M('infrastructure',['infra','struct','ure'],[1],['struct = build','structure','infrastructure'],'Roads are part of infrastructure.'),M('form',['form'],[0],['form = shape','form','shape or create'],'Ice can form overnight.'),M('reform',['re','form'],[1],['form = shape','reform','form again/change'],'The law was reformed.'),M('transform',['trans','form'],[1],['form = shape','transform','change form'],'Heat can transform the material.'),M('uniform',['uni','form'],[1],['form = shape','uniform','same form/standard clothing'],'The team wore a uniform.'),M('formation',['form','ation'],[0],['form = shape','form','formation'],'Cloud formation changed.'),M('information',['in','form','ation'],[1],['form = shape','word family clue','information'],'The chart gives information.'),M('transformation',['trans','form','ation'],[1],['form = shape','transform','transformation'],'The caterpillar undergoes transformation.'),M('formulation',['form','ul','ation'],[0],['form = shape','formulate','formulation'],'Scientists tested the formulation.'),M('deformed',['de','form','ed'],[1],['form = shape','deform','deformed'],'Heat deformed the plastic.') ]},
 '11':{label:'11. port & tract',group:'Roots & Word Families',items:[M('transport',['trans','port'],[1],['port = carry','transport','carry across/move'],'Trucks transport goods.'),M('portable',['port','able'],[0],['port = carry','portable','able to be carried'],'A laptop is portable.'),M('import',['im','port'],[1],['port = carry','import','bring in'],'The country imports fruit.'),M('export',['ex','port'],[1],['port = carry','export','send out'],'The company exports goods.'),M('transportation',['trans','port','ation'],[1],['port = carry','transport','transportation'],'Public transportation carries people.'),M('transporter',['trans','port','er'],[1],['port = carry','transport','transporter'],'The vehicle is a transporter.'),M('attract',['at','tract'],[1],['tract = pull/draw','attract','draw toward'],'Flowers attract bees.'),M('distract',['dis','tract'],[1],['tract = pull/draw','distract','draw attention away'],'Noise can distract readers.'),M('subtract',['sub','tract'],[1],['tract = pull/draw','subtract','take away'],'Subtract 4 from 10.'),M('extract',['ex','tract'],[1],['tract = pull/draw','extract','pull/take out'],'Extract the key information.'),M('attraction',['at','tract','ion'],[1],['tract = pull/draw','attract','attraction'],'The exhibit is a popular attraction.'),M('distraction',['dis','tract','ion'],[1],['tract = pull/draw','distract','distraction'],'The noise was a distraction.'),M('contraction',['con','tract','ion'],[1],['tract = pull/draw','contract','contraction'],'The muscle contraction was visible.'),M('tractor',['tract','or'],[0],['tract = pull/draw','tractor','a machine that pulls'],'The tractor crossed the field.'),M('extractor',['ex','tract','or'],[1],['tract = pull/draw','extract','extractor'],'The extractor removed the air.'),M('contractual',['con','tract','ual'],[1],['tract = pull/draw','contract','contractual'],'The agreement created contractual duties.') ]},
 '12':{label:'12. spect & dict',group:'Roots & Word Families',items:[M('inspect',['in','spect'],[1],['spect = look/see','inspect','look closely'],'Inspect the equipment.'),M('respect',['re','spect'],[1],['spect = look/see','respect','context refines the modern meaning'],'Show respect to others.'),M('spectator',['spect','ator'],[0],['spect = look/see','spectator','a person who watches'],'The spectator cheered.'),M('spectacle',['spect','acle'],[0],['spect = look/see','spectacle','something seen/displayed'],'The parade was a spectacle.'),M('inspection',['in','spect','ion'],[1],['spect = look/see','inspect','inspection'],'The bridge passed inspection.'),M('perspective',['per','spect','ive'],[1],['spect = look/see','perspective','a way of viewing'],'Consider another perspective.'),M('retrospective',['retro','spect','ive'],[1],['spect = look/see','look back','retrospective'],'The exhibit was retrospective.'),M('predict',['pre','dict'],[1],['dict = say/tell','predict','say beforehand'],'Predict what happens next.'),M('dictate',['dict','ate'],[0],['dict = say/tell','dictate','say aloud for another to write'],'The teacher dictated the sentence.'),M('dictionary',['dict','ionary'],[0],['dict = say/tell','word family clue','dictionary'],'Use a dictionary.'),M('verdict',['ver','dict'],[1],['dict = say/tell','verdict','formal decision stated'],'The jury reached a verdict.'),M('prediction',['pre','dict','ion'],[1],['dict = say/tell','predict','prediction'],'Write your prediction.'),M('contradiction',['contra','dict','ion'],[1],['dict = say/tell','contradict','contradiction'],'The statements contain a contradiction.'),M('predictable',['pre','dict','able'],[1],['dict = say/tell','predict','predictable'],'The pattern became predictable.'),M('contradictory',['contra','dict','ory'],[1],['dict = say/tell','contradict','contradictory'],'The answers were contradictory.'),M('dictator',['dict','ator'],[0],['dict = say/tell','dictate','dictator'],'The text described a dictator.') ]},
 '13':{label:'13. ject & cred',group:'Roots & Word Families',items:[M('project',['pro','ject'],[1],['ject = throw','project','context refines the modern meaning'],'The class began a project.'),M('projection',['pro','ject','ion'],[1],['ject = throw','project','projection'],'The projection appeared on the wall.'),M('inject',['in','ject'],[1],['ject = throw','inject','put into'],'The nurse will inject the medicine.'),M('injection',['in','ject','ion'],[1],['ject = throw','inject','injection'],'The injection was quick.'),M('reject',['re','ject'],[1],['ject = throw','reject','throw back/refuse'],'The editor may reject the draft.'),M('rejection',['re','ject','ion'],[1],['ject = throw','reject','rejection'],'The proposal faced rejection.'),M('subject',['sub','ject'],[1],['ject = throw','family clue','subject'],'The subject was science.'),M('projectile',['pro','ject','ile'],[1],['ject = throw','project','projectile'],'The launcher sent a projectile forward.'),M('interjection',['inter','ject','ion'],[1],['ject = throw','interject','interjection'],'Wow is an interjection.'),M('injectable',['in','ject','able'],[1],['ject = throw','inject','injectable'],'The medicine is injectable.'),M('credible',['cred','ible'],[0],['cred = believe/trust','credible','able to be believed'],'The source was credible.'),M('incredible',['in','cred','ible'],[1],['cred = believe/trust','incredible','not believable / amazing'],'The view was incredible.'),M('credibility',['cred','ibil','ity'],[0],['cred = believe/trust','credible','credibility'],'Evidence increased her credibility.'),M('credit',['cred','it'],[0],['cred = believe/trust','credit','trust/recognition'],'Give credit to the author.'),M('credentials',['cred','ential','s'],[0],['cred = believe/trust','credential','credentials'],'The applicant listed credentials.'),M('discredit',['dis','cred','it'],[1],['cred = believe/trust','discredit','reduce trust'],'False claims can discredit a source.'),M('credibly',['cred','ibly'],[0],['cred = believe/trust','credible','credibly'],'She explained the result credibly.') ]},
 '14':{label:'14. bio & geo',group:'Roots & Word Families',items:[M('biology',['bio','logy'],[0],['bio = life','-logy = study of','study of life'],'Biology is the study of living things.'),M('biologist',['bio','log','ist'],[0],['bio = life','biologist','a scientist who studies life'],'A biologist examined the sample.'),M('biography',['bio','graphy'],[0],['bio = life','graphy = writing','writing about a life'],'She read a biography.'),M('biodiversity',['bio','diversity'],[0],['bio = life','diversity','variety of living things'],'The rainforest has high biodiversity.'),M('biome',['bio','me'],[0],['bio = life','biome','large ecological region'],'The desert is a biome.'),M('autobiography',['auto','bio','graphy'],[1],['bio = life','auto = self','writing about one’s own life'],'He wrote an autobiography.'),M('biodegradable',['bio','degrad','able'],[0],['bio = life','-able','able to break down biologically'],'The container is biodegradable.'),M('geography',['geo','graphy'],[0],['geo = earth','graphy = writing/recording','study/description of Earth places'],'We studied geography.'),M('geographic',['geo','graph','ic'],[0],['geo = earth','geographic','related to geography'],'The map shows geographic regions.'),M('geology',['geo','logy'],[0],['geo = earth','-logy = study of','study of Earth'],'Geology explains rocks and landforms.'),M('geologist',['geo','log','ist'],[0],['geo = earth','geologist','scientist who studies Earth'],'A geologist collected rocks.'),M('geometry',['geo','metry'],[0],['geo = earth','metry = measure','historical root connection to measuring'],'Geometry studies shapes.'),M('geothermal',['geo','thermal'],[0],['geo = earth','thermal = heat','heat from Earth'],'The building uses geothermal energy.'),M('geologic',['geo','log','ic'],[0],['geo = earth','geology','geologic'],'The canyon reveals geologic layers.'),M('geographer',['geo','graph','er'],[0],['geo = earth','geography','geographer'],'A geographer studies places.'),M('biographical',['bio','graph','ical'],[0],['bio = life','graph = write','biographical'],'The article included biographical details.') ]},
 '15':{label:'15. photo, tele & scope',group:'Roots & Word Families',items:[M('photograph',['photo','graph'],[0],['photo = light','graph = record/write','photograph'],'She took a photograph.'),M('photography',['photo','graphy'],[0],['photo = light','graphy = recording','photography'],'He studies photography.'),M('photosynthesis',['photo','synthesis'],[0],['photo = light','synthesis','light is central to the process'],'Plants use photosynthesis.'),M('photographic',['photo','graph','ic'],[0],['photo = light','graph = record','photographic'],'They found photographic evidence.'),M('photometer',['photo','meter'],[0],['photo = light','meter = measure','instrument for measuring light'],'The photometer measured brightness.'),M('photosensitive',['photo','sensitive'],[0],['photo = light','sensitive','sensitive to light'],'The material is photosensitive.'),M('telephone',['tele','phone'],[0],['tele = far','phone = sound/voice','sound across distance'],'The telephone rang.'),M('television',['tele','vision'],[0],['tele = far','vision = seeing','seeing across distance'],'The news was on television.'),M('telescope',['tele','scope'],[0,1],['tele = far','scope = view','tool for viewing faraway objects'],'We used a telescope.'),M('telescopic',['tele','scope','ic'],[0,1],['tele = far','scope = view','telescopic'],'The camera had a telescopic lens.'),M('teleconference',['tele','conference'],[0],['tele = far','conference','meeting across distance'],'They joined a teleconference.'),M('telephoto',['tele','photo'],[0,1],['tele = far','photo = light','photography from a distance'],'He used a telephoto lens.'),M('microscope',['micro','scope'],[1],['scope = view','micro = small','tool for viewing tiny things'],'Use a microscope to see cells.'),M('microscopic',['micro','scope','ic'],[1],['scope = view','micro = small','microscopic'],'The particles were microscopic.'),M('periscope',['peri','scope'],[1],['scope = view','peri = around','viewing instrument'],'The submarine raised its periscope.'),M('telescopically',['tele','scope','ic','ally'],[0,1],['tele = far','scope = view','telescopically'],'The sections extend telescopically.') ]},
 '16':{label:'16. graph/gram, phon & logy',group:'Roots & Word Families',items:[M('graph',['graph'],[0],['graph = write/record','graph','recorded representation'],'The graph shows the data.'),M('graphic',['graph','ic'],[0],['graph = write/record','graphic','visual/recorded form'],'Add a graphic to the page.'),M('paragraph',['para','graph'],[1],['graph = write/record','paragraph','a section of writing'],'Read the paragraph.'),M('diagram',['dia','gram'],[1],['gram = something written/recorded','diagram','visual representation'],'Label the diagram.'),M('phonics',['phon','ics'],[0],['phon = sound/voice','phonics','study/use of sound-spelling relationships'],'We practiced phonics.'),M('microphone',['micro','phone'],[1],['phon = sound/voice','microphone','device for sound'],'Speak into the microphone.'),M('symphony',['sym','phon','y'],[1],['phon = sound/voice','symphony','musical sound composition'],'The orchestra played a symphony.'),M('telephone',['tele','phone'],[1],['phon = sound/voice','telephone','sound across distance'],'The telephone rang.'),M('biology',['bio','logy'],[1],['-logy = study of','bio = life','study of life'],'Biology studies living things.'),M('geology',['geo','logy'],[1],['-logy = study of','geo = earth','study of Earth'],'Geology studies Earth.'),M('ecology',['eco','logy'],[1],['-logy = study of','eco','study of relationships in environments'],'Ecology examines ecosystems.'),M('zoology',['zoo','logy'],[1],['-logy = study of','zoo = animal','study of animals'],'Zoology focuses on animals.'),M('phonograph',['phono','graph'],[0,1],['phon = sound','graph = record','device that records/plays sound'],'The museum displayed a phonograph.'),M('audiogram',['audio','gram'],[1],['gram = record','audio = hearing/sound','record of hearing results'],'The audiogram showed hearing levels.'),M('oceanography',['ocean','o','graphy'],[2],['graphy = recording/study','ocean','study of oceans'],'Oceanography examines oceans.'),M('seismology',['seismo','logy'],[1],['-logy = study of','seismo = earthquakes','study of earthquakes'],'Seismology studies earthquakes.'),M('logarithm',['log','arithm'],[],['use syllable and context clues','logarithm','mathematical term'],'The calculator found the logarithm.') ]},
 '17':{label:'17. Mixed Latin & Greek Analysis',group:'Transfer & Application',items:[M('reconstruction',['re','con','struct','ion'],[2],['struct = build','reconstruct','reconstruction'],'The bridge reopened after reconstruction.'),M('transportation',['trans','port','ation'],[1],['port = carry','transport','transportation'],'Public transportation moved people.'),M('contradictory',['contra','dict','ory'],[1],['dict = say/tell','contradict','contradictory'],'The explanations were contradictory.'),M('credibility',['cred','ibil','ity'],[0],['cred = believe/trust','credible','credibility'],'Evidence increased credibility.'),M('biodiversity',['bio','diversity'],[0],['bio = life','diversity','variety of living things'],'The wetland supports biodiversity.'),M('geothermal',['geo','thermal'],[0],['geo = earth','thermal = heat','heat from Earth'],'The system uses geothermal energy.'),M('microscopic',['micro','scope','ic'],[1],['scope = view','micro = small','microscopic'],'The cells are microscopic.'),M('photography',['photo','graphy'],[0],['photo = light','graphy = recording','photography'],'Photography uses light to capture images.'),M('microphone',['micro','phone'],[1],['phon = sound','microphone','device for sound'],'Use the microphone.'),M('biographical',['bio','graph','ical'],[0,1],['bio = life','graph = write','biographical'],'The text included biographical details.'),M('projected',['pro','ject','ed'],[1],['ject = throw','project','projected'],'The image was projected.'),M('geologist',['geo','log','ist'],[0],['geo = earth','geology','geologist'],'The geologist studied the cliff.'),M('inspection',['in','spect','ion'],[1],['spect = look','inspect','inspection'],'The building passed inspection.'),M('reformulation',['re','form','ul','ation'],[1],['form = shape','reformulate','reformulation'],'The scientist tried a reformulation.'),M('retrospectively',['retro','spect','ive','ly'],[1],['spect = look','retrospective','retrospectively'],'Retrospectively, the choice made sense.'),M('photobiology',['photo','bio','logy'],[0,1,2],['photo = light','bio = life','-logy = study of'],'Photobiology studies effects of light on living things.'),M('geographical',['geo','graph','ical'],[0,1],['geo = earth','graph = record','geographical'],'The map shows geographical features.'),M('projectionist',['pro','ject','ion','ist'],[1],['ject = throw','projection','projectionist'],'The projectionist prepared the film.') ]},
 '18':{label:'18. Independent Transfer',group:'Transfer & Application',items:[M('reconstruction',['re','con','struct','ion'],[2],['choose the strongest clue','build a tentative meaning','reread in context'],'Reconstruction of the bridge took months.'),M('biodegradable',['bio','degrad','able'],[0,2],['choose a useful clue','build a tentative meaning','check context/reference if needed'],'The biodegradable package broke down over time.'),M('unpredictable',['un','pre','dict','able'],[0,2,3],['choose efficient clues','build a tentative meaning','reread'],'The weather was unpredictable.'),M('telecommunications',['tele','communicat','ions'],[0],['tele = far','use only the useful clue','check another source if needed'],'Telecommunications connect people over distance.'),M('geographic',['geo','graph','ic'],[0,1],['geo = earth','graph = record','geographic'],'The map shows geographic regions.'),M('inspection',['in','spect','ion'],[1],['spect = look','inspect','inspection'],'The inspection found no damage.'),M('photosynthesis',['photo','synthesis'],[0],['photo = light','tentative meaning only','context/source completes meaning'],'Photosynthesis allows plants to make food using light.'),M('credibility',['cred','ibil','ity'],[0],['cred = believe/trust','credible','credibility'],'Reliable evidence builds credibility.'),M('transportation',['trans','port','ation'],[1],['port = carry','transport','transportation'],'Transportation moves people and goods.'),M('reformulation',['re','form','ul','ation'],[1],['form = shape','reformulate','reformulation'],'The medicine required reformulation.'),M('retrospective',['retro','spect','ive'],[1],['spect = look','look back','retrospective'],'The museum opened a retrospective exhibit.'),M('photographic',['photo','graph','ic'],[0,1],['photo = light','graph = record','photographic'],'Photographic evidence supported the claim.'),M('contradiction',['contra','dict','ion'],[1],['dict = say/tell','contradict','contradiction'],'The two statements contain a contradiction.'),M('infrastructure',['infra','struct','ure'],[1],['struct = build','structure','infrastructure'],'Roads and bridges are infrastructure.'),M('telescopic',['tele','scope','ic'],[0,1],['tele = far','scope = view','telescopic'],'The device has a telescopic arm.'),M('biodiversity',['bio','diversity'],[0],['bio = life','diversity','biodiversity'],'Protecting habitats supports biodiversity.'),M('disconnected',['dis','connect','ed'],[0,2],['connect','disconnect','disconnected'],'The cable was disconnected.'),M('projection',['pro','ject','ion'],[1],['ject = throw','project','projection'],'The projection filled the wall.'),M('geologist',['geo','log','ist'],[0],['geo = earth','geology','geologist'],'The geologist examined the rock layers.'),M('predictable',['pre','dict','able'],[1],['dict = say/tell','predict','predictable'],'The repeated pattern became predictable.') ]}
};
const moSkill=$('#moSkill');
['Foundations','Affixes & Multisyllabic','Roots & Word Families','Transfer & Application'].forEach(g=>{const og=document.createElement('optgroup');og.label=g;Object.entries(morphologyBanks).filter(([,v])=>v.group===g).forEach(([k,v])=>og.append(new Option(v.label,k)));moSkill.append(og)});
let mo={seq:[],i:0,step:-1,t:null,paused:false,mode:'guided',cyclePhase:'word'};const stepNames=['SPOT','SPLIT','READ','BUILD','CHECK'];
$('#moMode').addEventListener('change',()=>$('#moCycleOptions').classList.toggle('hidden',$('#moMode').value!=='cycle'));
$('#moStart').addEventListener('click',startMo);$('#moRestart').addEventListener('click',startMo);$('#moNext').addEventListener('click',()=>{mo.i++;if(mo.i>=mo.seq.length)return moDone();mo.step=-1;moGuidedWord()});$('#moAction').addEventListener('click',()=>{if(mo.mode==='guided')moAdvance();else if(mo.cyclePhase==='reveal')moCycleNext()});$('#moPause').addEventListener('click',()=>{mo.paused=!mo.paused;clearTimeout(mo.t);$('#moPause').textContent=mo.paused?'Resume':'Pause';if(!mo.paused)moCycleWord()});
function startMo(){clearTimeout(mo.t);mo.mode=$('#moMode').value;mo.seq=fillSequence(morphologyBanks[moSkill.value].items,Number($('#moCount').value));mo.i=0;mo.step=-1;mo.paused=false;$('#moPause').textContent='Pause';$('#moRestart').classList.remove('hidden');if(mo.mode==='guided')moGuidedWord();else moCycleWord()}
function fitWord(el,text){el.textContent=text;const n=text.length;el.style.fontSize=n>18?'clamp(2.2rem,5.5vw,4.6rem)':n>13?'clamp(2.7rem,7vw,5.6rem)':''}
function resetMoButtons(){['#moAction','#moNext','#moPause'].forEach(s=>$(s).classList.add('hidden'))}
function activateMoStep(i){$$('#moSteps span').forEach((x,n)=>x.classList.toggle('active',n===i))}
function moGuidedWord(){resetMoButtons();activateMoStep(-1);const item=mo.seq[mo.i];fitWord($('#moWord'),item.w);$('#moVisual').innerHTML='';$('#moPrompt').textContent='What useful part do you notice?';$('#moAction').textContent='SPOT';$('#moAction').classList.remove('hidden');setCounter('#moCounter',mo.i,mo.seq.length)}
function moAdvance(){const item=mo.seq[mo.i];mo.step++;activateMoStep(mo.step);resetMoButtons();if(mo.step===0){fitWord($('#moWord'),item.w);renderChunks(item,item.spot);$('#moPrompt').textContent='SPOT: Notice a useful part, pattern, base, affix, or root.'}
 if(mo.step===1){$('#moWord').textContent='';renderChunks(item,item.parts.map((_,i)=>i),true);$('#moPrompt').textContent='SPLIT: Separate the useful parts so you can work with them.'}
 if(mo.step===2){$('#moWord').textContent='';$('#moVisual').innerHTML=`<div class="chunk-row">${item.parts.map((p,i)=>`${i?'<span class="read-arrow">→</span>':''}<span class="chunk">${escapeHtml(p)}</span>`).join('')}</div><div class="read-arrow" style="margin-top:12px">↓</div><div class="whole-small">${escapeHtml(item.w)}</div>`;$('#moPrompt').textContent='READ: Read the parts, then bring them back together and read the whole word smoothly.'}
 if(mo.step===3){$('#moWord').textContent='';$('#moVisual').innerHTML=`<div class="build-chain">${item.build.map((b,i)=>`${i?'<span class="read-arrow">→</span>':''}<span class="build-piece ${i===item.build.length-1?'final':''}">${escapeHtml(b)}</span>`).join('')}</div>`;$('#moPrompt').textContent='BUILD: Use the meaningful parts to build a reasonable meaning.'}
 if(mo.step===4){fitWord($('#moWord'),item.w);$('#moVisual').innerHTML=`<div class="sentence-card">${escapeHtml(item.check)}</div>`;$('#moPrompt').textContent='CHECK: Does the meaning fit? Reread the whole sentence.'}
 if(mo.step<4){$('#moAction').textContent=stepNames[mo.step+1];$('#moAction').classList.remove('hidden')}else $('#moNext').classList.remove('hidden')}
function renderChunks(item,highlight=[],showBars=false){$('#moVisual').innerHTML=`<div class="chunk-row">${item.parts.map((p,i)=>`${i&&showBars?'<span class="bar">|</span>':''}<span class="chunk ${highlight.includes(i)?'focus':''}">${escapeHtml(p)}</span>`).join('')}</div>`}
function moCycleWord(){if(mo.paused)return;if(mo.i>=mo.seq.length)return moDone();resetMoButtons();activateMoStep(-1);const item=mo.seq[mo.i];mo.cyclePhase='word';fitWord($('#moWord'),item.w);$('#moVisual').innerHTML='';$('#moPrompt').textContent='Read it.';$('#moPause').classList.remove('hidden');setCounter('#moCounter',mo.i,mo.seq.length);mo.t=setTimeout(moCycleThink,Number($('#moWordTime').value))}
function moCycleThink(){if(mo.paused)return;mo.cyclePhase='think';$('#moWord').textContent='';$('#moVisual').innerHTML='';$('#moPrompt').textContent='Where would you split it? What meaning can you build?';mo.t=setTimeout(moCycleReveal,Number($('#moThinkTime').value))}
function moCycleReveal(){if(mo.paused)return;const item=mo.seq[mo.i];mo.cyclePhase='reveal';fitWord($('#moWord'),item.w);$('#moVisual').innerHTML=`<div class="discussion-label">Split + Build</div><div class="chunk-row">${item.parts.map((p,i)=>`${i?'<span class="bar">|</span>':''}<span class="chunk focus">${escapeHtml(p)}</span>`).join('')}</div><div class="build-chain" style="margin-top:18px">${item.build.map((b,i)=>`${i?'<span class="read-arrow">→</span>':''}<span class="build-piece ${i===item.build.length-1?'final':''}">${escapeHtml(b)}</span>`).join('')}</div>`;$('#moPrompt').textContent='Discuss the split. Build the meaning. Reread the whole word.';const rt=$('#moRevealTime').value;if(rt==='teacher'){$('#moPause').classList.add('hidden');$('#moAction').textContent='Next Word';$('#moAction').classList.remove('hidden')}else{mo.t=setTimeout(moCycleNext,Number(rt))}}
function moCycleNext(){clearTimeout(mo.t);mo.i++;moCycleWord()}
function moDone(){clearTimeout(mo.t);resetMoButtons();activateMoStep(-1);$('#moWord').style.fontSize='';$('#moWord').textContent='Complete';$('#moVisual').innerHTML='';$('#moPrompt').textContent='';$('#moCounter').textContent=`${mo.seq.length} words`}
function setCounter(sel,i,n){$(sel).textContent=`Word ${i+1} of ${n}`}
